### PR TITLE
Adding resolve.fallback to remove polyfill errors while using package

### PR DESCRIPTION
**Pull request by Devender1703**
While trying to use package web3-login in react app (created using CRA).

We encounter polyfill errors while building user app 

https://pastebin.com/4qvwjGgX. 

This is due to the default webpack config present in users app doesn't contain fallback properties.
https://webpack.js.org/configuration/resolve/#resolvefallback

we need a way to override user app's webpack config to solve this issue.

### CODE REVIEW

**Comment by theshadowagent** [comment]
Thanks for the PR! Unfortunately, to fix polyfill errors in the npm package, we need to override `rollup.config.js` instead of `craco.config.js`
Craco (fork of CRA with overridable webpack config) is used only to test this library locally, and I'm not getting polyfill errors when I run this library locally with `yarn start`. Do you have them?

**Comment by theshadowagent** [comment]
I was planning to make this library work by finishing migrating to [preconstruct](https://preconstruct.tools/) sometime next week, it still has a strange error in `next.js`. However, I'd appreciate your PR to fix polyfill errors in `rollup`


You can build the library locally by running in the package root directory (most probably named `web3-login`)

```
yarn build
```
And to test the build run this in your CRA project folder
```
yarn add link:./../web3-login
```
Then import normally
```javascript
import { Web3Provider } from "@buildship/web3-login";

...
```

**Comment by Devender1703** [comment]
Done some changes in rollup config to add polyfills and added package rollup-plugin-node-polyfills.
Still the user app is giving same error.

**Comment by Devender1703** [comment]
last commit is removing polyfill errors but the main login app is still not coming and console is showing following errors 
https://pastebin.com/jweXHMuH

**Comment by Devender1703** [comment]
Dev console errors

dev console error

**Pull request closed without merging**
